

Bienvenido a la redirección de pagofacil.


<?php

$params = Mage::app()->getRequest()->getParams();

$enviroment = Mage::helper('pagofacildirect/Data')->verificaTDSecureConfig();

?>

<script type="text/javascript">

    var campos   = '<?php echo $params['params'] ?>';
    var ambiente = '<?php echo $enviroment ?>';
    var params   = Base64.encode(campos);

    switch (ambiente) {
        case '1':
            //1 produccion
            var send = 'https://api.pagofacil.tech/Wsrtransaccion/index/format/json';
        break;
        default:
            //2 sanbox
            var send = 'https://sandbox.pagofacil.tech/Wsrtransaccion/index/format/json';
        break;
    }

    document.body.innerHTML += '<form id="sendForm" action="'+send+'" method="post"><input type="hidden" name="contenido" value='+params+' id='+params+'></form>';

    document.getElementById("sendForm").submit();

</script>